Repository etcd-io/raft, pull requests merged in 2025-02, with the labels that each got.

#259 [3.6] Remove changelog from `release-3.6`
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/M, approved

#260 Update golang toolchain to 1.23.6
  .go-version
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/XS, approved

#261 [3.6] Update golang toolchain to 1.23.6
  .go-version
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/XS, approved

#262 Update changelog for v3.6.0
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#265 Add code of conduct
  code-of-conduct.md
Labels: size/XS, approved

#269 Bump go linter 1.24
  .github/workflows/static-analysis.yaml
Labels: size/XS, approved

#271 bump golangci-lint v1.64.5
  .github/workflows/static-analysis.yaml
Labels: size/XS, approved

#268 Bump go 1.24.0
  .go-version
  go.mod
Labels: size/XS, approved
